### ISSUE TITLE
AttributeError: 'MixFormerOnline' object has no attribute 'online_sizes'

### ISSUE THREAD

**Issue by hopeSerendipity** [MCG-NJU/MixFormer#107]
再跑run_video_demo.sh时遇到的报错，全部报错如下：
Load checkpoint /home/data/MixFormer/models/mixformer_convmae_base_online.pth.tar successfully!
Traceback (most recent call last):
  File "tracking/video_demo.py", line 53, in <module>
    main()
  File "tracking/video_demo.py", line 49, in main
    args.save_results, tracker_params=tracker_params)
  File "tracking/video_demo.py", line 21, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "tracking/../lib/test/evaluation/tracker.py", line 175, in run_video
    tracker = self.create_tracker(params)
  File "tracking/../lib/test/evaluation/tracker.py", line 65, in create_tracker
    tracker = self.tracker_class(params, self.dataset_name)
  File "tracking/../lib/test/tracker/mixformer_convmae_online.py", line 44, in __init__
    self.online_size = self.online_sizes[0]
AttributeError: 'MixFormerOnline' object has no attribute 'online_sizes'

**Comment by MaximeDebarbat** [comment]
Hi, I fixed it on `vit_online` by replacing this:

```
        else:
            self.update_intervals = self.cfg.DATA.MAX_SAMPLE_INTERVAL
            self.online_size = 3
        self.update_interval = self.update_intervals[0]
        self.online_size = self.online_sizes[0]
```
By this:
```
        else:
            self.update_intervals = self.cfg.DATA.MAX_SAMPLE_INTERVAL
            self.online_sizes = [3]
        self.update_interval = self.update_intervals[0]
        self.online_size = self.online_sizes[0]
``` 

and then it worked for me.
